version: '3.8'
services:
  db:
    image: postgres
    container_name: receipthub_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  receipts_hub:
    build: .
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    container_name: receipts_hub_app
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
